#!/bin/bash
ORIG_PATH=`pwd`
VBARS_PATH=`pwd`/vbars
VBARS=`pwd`/vbars/vbars
cd $VBARS_PATH
if hash nim 2>/dev/null; then
	echo "Nim is installed, compiling"
	nim c vbars.nim > /dev/null
	sudo ln -s $VBARS /usr/local/bin/.
else
    echo "Nim is not installed"
fi


cd $ORIG_PATH
TOSS=`pwd`/toss
sudo ln -s $TOSS /usr/local/bin/.

unamestr=`uname`

if [[ $unamestr == 'Linux' ]]; then
	sudo apt-get install youtube-dl
elif [[ $unamestr == 'Darwin' ]]; then
	if hash brew 2>/dev/null; then
		brew install youtube-dl
	else
		echo "Brew is not installed, can't get youtube-dl"
		exit 1
	fi
fi

YOU=`pwd`/yoump3
sudo ln -s $YOU /usr/local/bin/.