#!/bin/bash
sudo env PATH=$PATH
ORIG_PATH=`pwd`
VBARS_PATH=`pwd`/vbars
VBARS=`pwd`/vbars/vbars
cd $VBARS_PATH
nim c vbars.nim
sudo ln -s $VBARS /usr/local/bin/.

cd $ORIG_PATH
TOSS=`pwd`/toss
sudo ln -s $TOSS /usr/local/bin/.

unamestr=`uname`

if [[ $unamestr == 'Linux' ]]; then
	sudo apt-get install youtube-dl
elif [[ $unamestr == 'Darwin' ]]; then
	brew install youtube-dl
fi

YOU=`pwd`/yoump3
sudo ln -s $YOU /usr/local/bin/.