/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nimrod/0.10.2/nim/lib -o /Users/oxu/Tools/vbars/nimcache/algorithm.o /Users/oxu/Tools/vbars/nimcache/algorithm.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct datapair129013 datapair129013;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY129019 TY129019;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct datapair129013 {
NimStringDesc* Field0;
NF Field1;
};
typedef struct {
N_NIMCALL_PTR(NI, ClPrc) (datapair129013 x_129228, datapair129013 y_129230, void* ClEnv);
void* ClEnv;
} TY129234;
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CLOSURE_PTR(NI, TMP285) (datapair129013 x_129303, datapair129013 y_129305);
typedef N_CLOSURE_PTR(NI, TMP287) (datapair129013 x_129303, datapair129013 y_129305);
struct TY129019 {
  TGenericSeq Sup;
  datapair129013 data[SEQ_DECL_SIZE];
};
static N_INLINE(NI, HEX2A_128020)(NI x, NU8 order);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_19001)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, merge_129276)(datapair129013* a_129284, NI a_129284Len0, datapair129013* b_129292, NI b_129292Len0, NI lo_129296, NI m_129298, NI hi_129300, TY129234 cmp_129308, NU8 order_129311);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(void, failedassertimpl_85425)(NimStringDesc* msg);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NI, mulInt)(NI a, NI b);
STRING_LITERAL(TMP286, "j (system.<=|system.<=|system.<=|system.<=|system.<=|system.<=|"
"system.<=|system.<=|system.<=|system.<=|system.<=|system.<=|syst"
"em.<=|system.<=|system.<=|...)\012    m ", 164);
extern TFrame* frameptr_16442;
extern TNimType NTI129019; /* seq[DataPair] */

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16442 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16442).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16442;
	frameptr_16442 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_19001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16442 = (*frameptr_16442).prev;
}

static N_INLINE(NI, HEX2A_128020)(NI x, NU8 order) {
	NI result;
	NI y;
	NI TMP260;
	NI TMP261;
	nimfr("*", "algorithm.nim")
	result = 0;
	nimln(24, "algorithm.nim");
	nimln(24, "algorithm.nim");
	nimln(24, "algorithm.nim");
	TMP260 = subInt(((NI) (order)), 1);
	y = (NI64)(TMP260);
	nimln(25, "algorithm.nim");
	nimln(25, "algorithm.nim");
	nimln(25, "algorithm.nim");
	TMP261 = subInt((NI)(x ^ ((NI) (y))), ((NI) (y)));
	result = (NI64)(TMP261);
	popFrame();
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
	result = 0;
	{
		if (!(b == 0)) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == (IL64(-9223372036854775807) - IL64(1)));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == -1);
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI64)(a / b);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, merge_129276)(datapair129013* a_129284, NI a_129284Len0, datapair129013* b_129292, NI b_129292Len0, NI lo_129296, NI m_129298, NI hi_129300, TY129234 cmp_129308, NU8 order_129311) {
	NI j;
	NI bb;
	NI i;
	NI k;
	nimfr("merge", "algorithm.nim")
	nimln(118, "algorithm.nim");
	{
		NI TMP284;
		NI LOC3;
		NI LOC4;
		nimln(118, "algorithm.nim");
		nimln(118, "algorithm.nim");
		nimln(118, "algorithm.nim");
		if ((NU)(m_129298) >= (NU)(a_129284Len0)) raiseIndexError();
		nimln(118, "algorithm.nim");
		TMP284 = addInt(m_129298, 1);
		if ((NU)((NI64)(TMP284)) >= (NU)(a_129284Len0)) raiseIndexError();
		LOC3 = 0;
		LOC3 = cmp_129308.ClEnv? cmp_129308.ClPrc(a_129284[m_129298], a_129284[(NI64)(TMP284)], cmp_129308.ClEnv):((TMP285)(cmp_129308.ClPrc))(a_129284[m_129298], a_129284[(NI64)(TMP284)]);
		LOC4 = 0;
		LOC4 = HEX2A_128020(LOC3, order_129311);
		if (!(LOC4 <= 0)) goto LA5;
		nimln(118, "algorithm.nim");
		goto BeforeRet;
	}
	LA5: ;
	nimln(119, "algorithm.nim");
	j = lo_129296;
	nimln(121, "algorithm.nim");
	{
		nimln(121, "algorithm.nim");
		nimln(121, "algorithm.nim");
		if (!!((j <= m_129298))) goto LA9;
		nimln(121, "algorithm.nim");
		failedassertimpl_85425(((NimStringDesc*) &TMP286));
	}
	LA9: ;
	nimln(123, "algorithm.nim");
	bb = 0;
	{
		nimln(124, "algorithm.nim");
		while (1) {
			nimln(124, "algorithm.nim");
			if (!(j <= m_129298)) goto LA12;
			nimln(111, "algorithm.nim");
			if ((NU)(bb) >= (NU)(b_129292Len0)) raiseIndexError();
			if ((NU)(j) >= (NU)(a_129284Len0)) raiseIndexError();
			unsureAsgnRef((void**) (&b_129292[bb].Field0), a_129284[j].Field0);
			b_129292[bb].Field1 = a_129284[j].Field1;
			nimln(126, "algorithm.nim");
			bb = addInt(bb, 1);
			nimln(127, "algorithm.nim");
			j = addInt(j, 1);
		} LA12: ;
	}
	nimln(131, "algorithm.nim");
	i = 0;
	nimln(132, "algorithm.nim");
	k = lo_129296;
	{
		nimln(134, "algorithm.nim");
		while (1) {
			NIM_BOOL LOC15;
			nimln(134, "algorithm.nim");
			LOC15 = 0;
			nimln(134, "algorithm.nim");
			LOC15 = (k < j);
			if (!(LOC15)) goto LA16;
			nimln(134, "algorithm.nim");
			LOC15 = (j <= hi_129300);
			LA16: ;
			if (!LOC15) goto LA14;
			nimln(135, "algorithm.nim");
			{
				NI LOC19;
				NI LOC20;
				nimln(135, "algorithm.nim");
				nimln(135, "algorithm.nim");
				nimln(135, "algorithm.nim");
				if ((NU)(i) >= (NU)(b_129292Len0)) raiseIndexError();
				if ((NU)(j) >= (NU)(a_129284Len0)) raiseIndexError();
				LOC19 = 0;
				LOC19 = cmp_129308.ClEnv? cmp_129308.ClPrc(b_129292[i], a_129284[j], cmp_129308.ClEnv):((TMP287)(cmp_129308.ClPrc))(b_129292[i], a_129284[j]);
				LOC20 = 0;
				LOC20 = HEX2A_128020(LOC19, order_129311);
				if (!(LOC20 <= 0)) goto LA21;
				nimln(111, "algorithm.nim");
				if ((NU)(k) >= (NU)(a_129284Len0)) raiseIndexError();
				if ((NU)(i) >= (NU)(b_129292Len0)) raiseIndexError();
				unsureAsgnRef((void**) (&a_129284[k].Field0), b_129292[i].Field0);
				a_129284[k].Field1 = b_129292[i].Field1;
				nimln(137, "algorithm.nim");
				i = addInt(i, 1);
			}
			goto LA17;
			LA21: ;
			{
				nimln(111, "algorithm.nim");
				if ((NU)(k) >= (NU)(a_129284Len0)) raiseIndexError();
				if ((NU)(j) >= (NU)(a_129284Len0)) raiseIndexError();
				unsureAsgnRef((void**) (&a_129284[k].Field0), a_129284[j].Field0);
				a_129284[k].Field1 = a_129284[j].Field1;
				nimln(140, "algorithm.nim");
				j = addInt(j, 1);
			}
			LA17: ;
			nimln(141, "algorithm.nim");
			k = addInt(k, 1);
		} LA14: ;
	}
	{
		nimln(144, "algorithm.nim");
		while (1) {
			nimln(144, "algorithm.nim");
			if (!(k < j)) goto LA25;
			nimln(111, "algorithm.nim");
			if ((NU)(k) >= (NU)(a_129284Len0)) raiseIndexError();
			if ((NU)(i) >= (NU)(b_129292Len0)) raiseIndexError();
			unsureAsgnRef((void**) (&a_129284[k].Field0), b_129292[i].Field0);
			a_129284[k].Field1 = b_129292[i].Field1;
			nimln(146, "algorithm.nim");
			k = addInt(k, 1);
			nimln(147, "algorithm.nim");
			i = addInt(i, 1);
		} LA25: ;
	}
	BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, sort_129215)(datapair129013* a_129223, NI a_129223Len0, TY129234 cmp_129233, NU8 order_129236) {
	NI n;
	TY129019* b;
	NI TMP281;
	NI s;
	nimfr("sort", "algorithm.nim")
	nimln(179, "algorithm.nim");
	nimln(179, "algorithm.nim");
	n = a_129223Len0;
	b = 0;
	nimln(181, "algorithm.nim");
	nimln(181, "algorithm.nim");
	TMP281 = divInt(n, 2);
	b = (TY129019*) newSeq((&NTI129019), (NI64)(TMP281));
	nimln(182, "algorithm.nim");
	s = 1;
	{
		nimln(183, "algorithm.nim");
		while (1) {
			NI m;
			NI TMP282;
			NI TMP283;
			NI TMP292;
			nimln(183, "algorithm.nim");
			if (!(s < n)) goto LA2;
			nimln(184, "algorithm.nim");
			nimln(184, "algorithm.nim");
			nimln(184, "algorithm.nim");
			TMP282 = subInt(n, 1);
			TMP283 = subInt((NI64)(TMP282), s);
			m = (NI64)(TMP283);
			{
				nimln(185, "algorithm.nim");
				while (1) {
					NI TMP288;
					NI TMP289;
					NI TMP290;
					NI TMP291;
					nimln(185, "algorithm.nim");
					if (!(0 <= m)) goto LA4;
					nimln(186, "algorithm.nim");
					nimln(186, "algorithm.nim");
					nimln(186, "algorithm.nim");
					nimln(186, "algorithm.nim");
					TMP288 = subInt(m, s);
					TMP289 = addInt((NI64)(TMP288), 1);
					nimln(186, "algorithm.nim");
					TMP290 = addInt(m, s);
					merge_129276(a_129223, a_129223Len0, b->data, b->Sup.len, (((NI64)(TMP289) >= 0) ? (NI64)(TMP289) : 0), m, (NI64)(TMP290), cmp_129233, order_129236);
					nimln(187, "algorithm.nim");
					nimln(187, "algorithm.nim");
					TMP291 = mulInt(s, 2);
					m = subInt(m, (NI64)(TMP291));
				} LA4: ;
			}
			nimln(188, "algorithm.nim");
			nimln(188, "algorithm.nim");
			TMP292 = mulInt(s, 2);
			s = (NI64)(TMP292);
		} LA2: ;
	}
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, HEX00_algorithmInit)(void) {
	nimfr("algorithm", "algorithm.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_algorithmDatInit)(void) {
}

