/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nimrod/0.10.2/nim/lib -o /Users/oxu/Tools/vbars/nimcache/niostream.o /Users/oxu/Tools/vbars/nimcache/niostream.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdio.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct charseq127019 charseq127019;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct charseq127019 {
  TGenericSeq Sup;
  NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(NIM_BOOL, iswhitespace_127027)(NIM_CHAR c);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_19001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NIM_BOOL, HEX3EHEX3E_127037)(FILE* strm, NimStringDesc** str);
N_NIMCALL(void, TMP257)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
NIM_CHAR lastchar_127023;
extern TFrame* frameptr_16442;
extern TNimType NTI147; /* char */
TNimType NTI127019; /* Charseq */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16442 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16442).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16442;
	frameptr_16442 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_19001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16442 = (*frameptr_16442).prev;
}

N_NIMCALL(NIM_BOOL, iswhitespace_127027)(NIM_CHAR c) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	NIM_BOOL LOC2;
	NIM_BOOL LOC3;
	nimfr("isWhitespace", "niostream.nim")
	result = 0;
	nimln(10, "niostream.nim");
	nimln(10, "niostream.nim");
	LOC1 = 0;
	nimln(10, "niostream.nim");
	LOC2 = 0;
	nimln(10, "niostream.nim");
	LOC3 = 0;
	nimln(10, "niostream.nim");
	LOC3 = ((NU8)(c) == (NU8)(32));
	if (LOC3) goto LA4;
	nimln(10, "niostream.nim");
	LOC3 = ((NU8)(c) == (NU8)(9));
	LA4: ;
	LOC2 = LOC3;
	if (LOC2) goto LA5;
	nimln(10, "niostream.nim");
	LOC2 = ((NU8)(c) == (NU8)(13));
	LA5: ;
	LOC1 = LOC2;
	if (LOC1) goto LA6;
	nimln(10, "niostream.nim");
	LOC1 = ((NU8)(c) == (NU8)(10));
	LA6: ;
	result = LOC1;
	popFrame();
	return result;
}
N_NIMCALL(void, TMP257)(void* p, NI op) {
	charseq127019* a;
	NI LOC1;
	a = (charseq127019*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}

N_NIMCALL(NIM_BOOL, HEX3EHEX3E_127037)(FILE* strm, NimStringDesc** str) {
	NIM_BOOL result;
	NIM_CHAR input;
	charseq127019* cseq;
	nimfr(">>", "niostream.nim")
	result = 0;
	nimln(14, "niostream.nim");
	input = 32;
	nimln(15, "niostream.nim");
	cseq = (charseq127019*) newSeq((&NTI127019), 0);
	{
		nimln(17, "niostream.nim");
		while (1) {
			NIM_BOOL LOC3;
			nimln(17, "niostream.nim");
			LOC3 = 0;
			LOC3 = iswhitespace_127027(input);
			if (!LOC3) goto LA2;
			nimln(18, "niostream.nim");
			input = fgetc(strm);
		} LA2: ;
	}
	nimln(20, "niostream.nim");
	{
		nimln(20, "niostream.nim");
		if (!(((NI) (((NU8)(input)))) == 255)) goto LA6;
		nimln(21, "niostream.nim");
		result = NIM_FALSE;
		nimln(22, "niostream.nim");
		goto BeforeRet;
	}
	LA6: ;
	nimln(24, "niostream.nim");
	cseq = (charseq127019*) incrSeq(&(cseq)->Sup, sizeof(NIM_CHAR));
	cseq->data[cseq->Sup.len-1] = input;
	{
		nimln(26, "niostream.nim");
		while (1) {
			NIM_BOOL LOC10;
			nimln(26, "niostream.nim");
			nimln(26, "niostream.nim");
			LOC10 = 0;
			nimln(26, "niostream.nim");
			LOC10 = iswhitespace_127027(input);
			if (LOC10) goto LA11;
			nimln(26, "niostream.nim");
			LOC10 = (((NI) (((NU8)(input)))) == 255);
			LA11: ;
			if (!!(LOC10)) goto LA9;
			nimln(27, "niostream.nim");
			input = fgetc(strm);
			nimln(28, "niostream.nim");
			{
				NIM_BOOL LOC14;
				nimln(28, "niostream.nim");
				nimln(28, "niostream.nim");
				LOC14 = 0;
				nimln(28, "niostream.nim");
				LOC14 = iswhitespace_127027(input);
				if (LOC14) goto LA15;
				nimln(28, "niostream.nim");
				LOC14 = (((NI) (((NU8)(input)))) == 255);
				LA15: ;
				if (!!(LOC14)) goto LA16;
				nimln(29, "niostream.nim");
				cseq = (charseq127019*) incrSeq(&(cseq)->Sup, sizeof(NIM_CHAR));
				cseq->data[cseq->Sup.len-1] = input;
			}
			LA16: ;
		} LA9: ;
	}
	nimln(31, "niostream.nim");
	unsureAsgnRef((void**) (&(*str)), copyString(((NimStringDesc*) (cseq))));
	nimln(32, "niostream.nim");
	nimln(32, "niostream.nim");
	nimln(32, "niostream.nim");
	nimln(32, "niostream.nim");
	result = !((cseq->Sup.len == 0));
	BeforeRet: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_niostreamInit)(void) {
	nimfr("niostream", "niostream.nim")
	nimln(7, "niostream.nim");
	lastchar_127023 = 32;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_niostreamDatInit)(void) {
NTI127019.size = sizeof(charseq127019*);
NTI127019.kind = 24;
NTI127019.base = (&NTI147);
NTI127019.flags = 2;
NTI127019.marker = TMP257;
}

