/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nimrod/0.10.2/nim/lib -o /Users/oxu/Tools/vbars/nimcache/vbars.o /Users/oxu/Tools/vbars/nimcache/vbars.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>

#include <stdio.h>

#include <stdlib.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tcell45335 tcell45335;
typedef struct TNimType TNimType;
typedef struct tcellseq45351 tcellseq45351;
typedef struct tgcheap47416 tgcheap47416;
typedef struct tcellset45347 tcellset45347;
typedef struct tpagedesc45343 tpagedesc45343;
typedef struct tmemregion27610 tmemregion27610;
typedef struct tsmallchunk26840 tsmallchunk26840;
typedef struct tllchunk27604 tllchunk27604;
typedef struct tbigchunk26842 tbigchunk26842;
typedef struct tintset26817 tintset26817;
typedef struct ttrunk26813 ttrunk26813;
typedef struct tavlnode27608 tavlnode27608;
typedef struct tgcstat47414 tgcstat47414;
typedef struct TY13406 TY13406;
typedef struct TY129019 TY129019;
typedef struct datapair129013 datapair129013;
typedef struct TNimNode TNimNode;
typedef struct charseq127019 charseq127019;
typedef struct tbasechunk26838 tbasechunk26838;
typedef struct tfreecell26830 tfreecell26830;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  tcell45335  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45351  {
NI Len;
NI Cap;
tcell45335** D;
};
struct  tcellset45347  {
NI Counter;
NI Max;
tpagedesc45343* Head;
tpagedesc45343** Data;
};
typedef tsmallchunk26840* TY27622[512];
typedef ttrunk26813* ttrunkbuckets26815[256];
struct  tintset26817  {
ttrunkbuckets26815 Data;
};
struct  tmemregion27610  {
NI Minlargeobj;
NI Maxlargeobj;
TY27622 Freesmallchunks;
tllchunk27604* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26842* Freechunkslist;
tintset26817 Chunkstarts;
tavlnode27608* Root;
tavlnode27608* Deleted;
tavlnode27608* Last;
tavlnode27608* Freeavlnodes;
};
struct  tgcstat47414  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47416  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45351 Zct;
tcellseq45351 Decstack;
tcellset45347 Cycleroots;
tcellseq45351 Tempstack;
NI Recgclock;
tmemregion27610 Region;
tgcstat47414 Stat;
};
struct datapair129013 {
NimStringDesc* Field0;
NF Field1;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef struct {
N_NIMCALL_PTR(NI, ClPrc) (datapair129013 x_129228, datapair129013 y_129230, void* ClEnv);
void* ClEnv;
} TY129234;
typedef N_CLOSURE_PTR(NI, TMP293) (datapair129013 x_129211, datapair129013 y_129213, void* ClEnv);
typedef N_CLOSURE_PTR(NI, TMP294) (datapair129013 x_130708, datapair129013 y_130710, void* ClEnv);
typedef NI TY26820[8];
struct  tpagedesc45343  {
tpagedesc45343* Next;
NI Key;
TY26820 Bits;
};
struct  tbasechunk26838  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26840  {
  tbasechunk26838 Sup;
tsmallchunk26840* Next;
tsmallchunk26840* Prev;
tfreecell26830* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27604  {
NI Size;
NI Acc;
tllchunk27604* Next;
};
struct  tbigchunk26842  {
  tbasechunk26838 Sup;
tbigchunk26842* Next;
tbigchunk26842* Prev;
NI Align;
NF Data;
};
struct  ttrunk26813  {
ttrunk26813* Next;
NI Key;
TY26820 Bits;
};
typedef tavlnode27608* TY27614[2];
struct  tavlnode27608  {
TY27614 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26830  {
tfreecell26830* Next;
NI Zerofield;
};
struct TY13406 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct TY129019 {
  TGenericSeq Sup;
  datapair129013 data[SEQ_DECL_SIZE];
};
struct charseq127019 {
  TGenericSeq Sup;
  NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(NimStringDesc*, paramstr_123809)(NI i);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell45335*, usrtocell_49046)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_19001)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_50604)(tcell45335* c);
N_NOINLINE(void, addzct_49017)(tcellseq45351* s, tcell45335* c);
N_NIMCALL(TY13406*, commandlineparams_124006)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP265)(void* p, NI op);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NF, nsuParseFloat)(NimStringDesc* s);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NIM_BOOL, HEX3EHEX3E_127037)(FILE* strm, NimStringDesc** str);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(NI, cmp_129195)(NF x_129199, NF y_129201);
N_NIMCALL(void, sort_129215)(datapair129013* a_129223, NI a_129223Len0, TY129234 cmp_129233, NU8 order_129236);
N_NIMCALL(void, merge_129276)(datapair129013* a_129284, NI a_129284Len0, datapair129013* b_129292, NI b_129292Len0, NI lo_129296, NI m_129298, NI hi_129300, TY129234 cmp_129308, NU8 order_129311);
N_NIMCALL(NI, HEX3Aanonymous_129189)(datapair129013 x, datapair129013 y);
N_NIMCALL(NI, HEX3Aanonymous_130689)(datapair129013 x, datapair129013 y);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(NimStringDesc*, nimFloatToStr)(NF f);
N_NIMCALL(void, failedassertimpl_85425)(NimStringDesc* msg);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_parseutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_parseutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_timesInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_timesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_posixInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_posixDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_osInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_osDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_niostreamInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_niostreamDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_algorithmInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_algorithmDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, vbarsInit)(void);
NIM_EXTERNC N_NOINLINE(void, vbarsDatInit)(void);
STRING_LITERAL(TMP266, "none", 4);
STRING_LITERAL(TMP267, "-r", 2);
STRING_LITERAL(TMP271, "-sd", 3);
STRING_LITERAL(TMP272, "down", 4);
STRING_LITERAL(TMP273, "-su", 3);
STRING_LITERAL(TMP274, "up", 2);
STRING_LITERAL(TMP275, "-sn", 3);
STRING_LITERAL(TMP276, "-h", 2);
STRING_LITERAL(TMP277, "-r [low] [high] : specify range", 31);
STRING_LITERAL(TMP278, "-su : sort up", 13);
STRING_LITERAL(TMP279, "-sd : sort down", 15);
STRING_LITERAL(TMP280, "-sn : don\'t sort", 16);
STRING_LITERAL(TMP295, "", 0);
STRING_LITERAL(TMP296, "+", 1);
STRING_LITERAL(TMP297, " ", 1);
STRING_LITERAL(TMP298, "(system.len|system.len|system.len|system.len|system.len|...)(a)"
" (system.==|system.==|system.==|system.==|system.==|system.==|sy"
"stem.==|system.==|system.==|system.==|system.==|system.==|system"
".==|system.==|system.==|system.==|system.==|system.==|system.==|"
"system.==|...)\012    L seq modified while iterating over it", 312);
NimStringDesc* programname_129004;
extern TFrame* frameptr_16442;
extern tgcheap47416 gch_47444;
TY13406* arguments_129008;
TY129019* values_129040;
TNimType NTI129013; /* DataPair */
extern TNimType NTI149; /* string */
extern TNimType NTI128; /* float */
TNimType NTI129019; /* seq[DataPair] */
NF low_129042;
NF high_129044;
NI i_129045;
NimStringDesc* sortmode_129046;
NimStringDesc* input_129149;
datapair129013 e_130822;
extern TNimType NTI127019; /* Charseq */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16442 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16442).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16442;
	frameptr_16442 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_19001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16442 = (*frameptr_16442).prev;
}

static N_INLINE(tcell45335*, usrtocell_49046)(void* usr) {
	tcell45335* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45335*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell45335))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50604)(tcell45335* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_49017((&gch_47444.Zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell45335* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_49046(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell45335* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_49046((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50604(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}
N_NIMCALL(void, TMP265)(void* p, NI op) {
	TY129019* a;
	NI LOC1;
	a = (TY129019*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field0, op);
	}
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell45335* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_49046(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_50604(c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI64)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, HEX3Aanonymous_129189)(datapair129013 x, datapair129013 y) {
	NI result;
	nimfr(":anonymous", "vbars.nim")
	result = 0;
	nimln(52, "vbars.nim");
	result = cmp_129195(x.Field1, y.Field1);
	popFrame();
	return result;
}

N_NIMCALL(NI, HEX3Aanonymous_130689)(datapair129013 x, datapair129013 y) {
	NI result;
	nimfr(":anonymous", "vbars.nim")
	result = 0;
	nimln(56, "vbars.nim");
	result = cmp_129195(y.Field1, x.Field1);
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit();
	HEX00_parseutilsDatInit();
	HEX00_strutilsDatInit();
	HEX00_timesDatInit();
	HEX00_posixDatInit();
	HEX00_osDatInit();
	HEX00_niostreamDatInit();
	HEX00_algorithmDatInit();
	vbarsDatInit();
	HEX00_parseutilsInit();
	HEX00_strutilsInit();
	HEX00_timesInit();
	HEX00_posixInit();
	HEX00_osInit();
	HEX00_niostreamInit();
	HEX00_algorithmInit();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	vbarsInit();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, vbarsInit)(void) {
	NimStringDesc* LOC1;
	nimfr("vbars", "vbars.nim")
	nimln(7, "vbars.nim");
	asgnRefNoCycle((void**) (&programname_129004), paramstr_123809(0));
	nimln(8, "vbars.nim");
	asgnRefNoCycle((void**) (&arguments_129008), commandlineparams_124006());
	nimln(14, "vbars.nim");
	if (values_129040) nimGCunrefNoCycle(values_129040);
	values_129040 = (TY129019*) newSeqRC1((&NTI129019), 0);
	nimln(15, "vbars.nim");
	low_129042 = 0.0;
	nimln(16, "vbars.nim");
	high_129044 = 1.0000000000000000e+02;
	nimln(17, "vbars.nim");
	i_129045 = 0;
	nimln(18, "vbars.nim");
	LOC1 = 0;
	LOC1 = sortmode_129046; sortmode_129046 = copyStringRC1(((NimStringDesc*) &TMP266));
	if (LOC1) nimGCunrefNoCycle(LOC1);
	{
		nimln(20, "vbars.nim");
		while (1) {
			nimln(20, "vbars.nim");
			nimln(20, "vbars.nim");
			if (!(i_129045 < arguments_129008->Sup.len)) goto LA3;
			nimln(21, "vbars.nim");
			{
				NI TMP269;
				NI TMP270;
				nimln(21, "vbars.nim");
				if ((NU)(i_129045) >= (NU)(arguments_129008->Sup.len)) raiseIndexError();
				if (!eqStrings(arguments_129008->data[i_129045], ((NimStringDesc*) &TMP267))) goto LA6;
				nimln(22, "vbars.nim");
				nimln(22, "vbars.nim");
				TMP269 = addInt(i_129045, 1);
				if ((NU)((NI64)(TMP269)) >= (NU)(arguments_129008->Sup.len)) raiseIndexError();
				low_129042 = nsuParseFloat(arguments_129008->data[(NI64)(TMP269)]);
				nimln(23, "vbars.nim");
				nimln(23, "vbars.nim");
				TMP270 = addInt(i_129045, 2);
				if ((NU)((NI64)(TMP270)) >= (NU)(arguments_129008->Sup.len)) raiseIndexError();
				high_129044 = nsuParseFloat(arguments_129008->data[(NI64)(TMP270)]);
				nimln(24, "vbars.nim");
				i_129045 = addInt(i_129045, 3);
			}
			goto LA4;
			LA6: ;
			{
				NimStringDesc* LOC11;
				nimln(25, "vbars.nim");
				if ((NU)(i_129045) >= (NU)(arguments_129008->Sup.len)) raiseIndexError();
				if (!eqStrings(arguments_129008->data[i_129045], ((NimStringDesc*) &TMP271))) goto LA9;
				nimln(26, "vbars.nim");
				LOC11 = 0;
				LOC11 = sortmode_129046; sortmode_129046 = copyStringRC1(((NimStringDesc*) &TMP272));
				if (LOC11) nimGCunrefNoCycle(LOC11);
				nimln(27, "vbars.nim");
				i_129045 = addInt(i_129045, 1);
			}
			goto LA4;
			LA9: ;
			{
				NimStringDesc* LOC15;
				nimln(28, "vbars.nim");
				if ((NU)(i_129045) >= (NU)(arguments_129008->Sup.len)) raiseIndexError();
				if (!eqStrings(arguments_129008->data[i_129045], ((NimStringDesc*) &TMP273))) goto LA13;
				nimln(29, "vbars.nim");
				LOC15 = 0;
				LOC15 = sortmode_129046; sortmode_129046 = copyStringRC1(((NimStringDesc*) &TMP274));
				if (LOC15) nimGCunrefNoCycle(LOC15);
				nimln(30, "vbars.nim");
				i_129045 = addInt(i_129045, 1);
			}
			goto LA4;
			LA13: ;
			{
				NimStringDesc* LOC19;
				nimln(31, "vbars.nim");
				if ((NU)(i_129045) >= (NU)(arguments_129008->Sup.len)) raiseIndexError();
				if (!eqStrings(arguments_129008->data[i_129045], ((NimStringDesc*) &TMP275))) goto LA17;
				nimln(32, "vbars.nim");
				LOC19 = 0;
				LOC19 = sortmode_129046; sortmode_129046 = copyStringRC1(((NimStringDesc*) &TMP266));
				if (LOC19) nimGCunrefNoCycle(LOC19);
				nimln(33, "vbars.nim");
				i_129045 = addInt(i_129045, 1);
			}
			goto LA4;
			LA17: ;
			{
				nimln(34, "vbars.nim");
				if ((NU)(i_129045) >= (NU)(arguments_129008->Sup.len)) raiseIndexError();
				if (!eqStrings(arguments_129008->data[i_129045], ((NimStringDesc*) &TMP276))) goto LA21;
				nimln(35, "vbars.nim");
				nimln(35, "vbars.nim");
				printf("%s\012", (((NimStringDesc*) &TMP277))->data);
				nimln(36, "vbars.nim");
				nimln(36, "vbars.nim");
				printf("%s\012", (((NimStringDesc*) &TMP278))->data);
				nimln(37, "vbars.nim");
				nimln(37, "vbars.nim");
				printf("%s\012", (((NimStringDesc*) &TMP279))->data);
				nimln(38, "vbars.nim");
				nimln(38, "vbars.nim");
				printf("%s\012", (((NimStringDesc*) &TMP280))->data);
				nimln(39, "vbars.nim");
				i_129045 = addInt(i_129045, 1);
				nimln(40, "vbars.nim");
				exit(0);
			}
			goto LA4;
			LA21: ;
			LA4: ;
		} LA3: ;
	}
	{
		nimln(45, "vbars.nim");
		while (1) {
			NIM_BOOL LOC25;
			NimStringDesc* numvalue;
			NIM_BOOL LOC26;
			datapair129013 LOC27;
			NimStringDesc* LOC28;
			nimln(45, "vbars.nim");
			LOC25 = 0;
			LOC25 = HEX3EHEX3E_127037(stdin, (&input_129149));
			if (!LOC25) goto LA24;
			numvalue = 0;
			nimln(47, "vbars.nim");
			nimln(47, "vbars.nim");
			LOC26 = 0;
			LOC26 = HEX3EHEX3E_127037(stdin, (&numvalue));
			nimln(48, "vbars.nim");
			memset((void*)(&LOC27), 0, sizeof(LOC27));
			LOC27.Field0 = copyString(input_129149);
			nimln(48, "vbars.nim");
			LOC27.Field1 = nsuParseFloat(numvalue);
			values_129040 = (TY129019*) incrSeq(&(values_129040)->Sup, sizeof(datapair129013));
			LOC28 = 0;
			LOC28 = values_129040->data[values_129040->Sup.len-1].Field0; values_129040->data[values_129040->Sup.len-1].Field0 = copyStringRC1(LOC27.Field0);
			if (LOC28) nimGCunrefNoCycle(LOC28);
			values_129040->data[values_129040->Sup.len-1].Field1 = LOC27.Field1;
		} LA24: ;
	}
	nimln(50, "vbars.nim");
	{
		TY129234 LOC33;
		nimln(50, "vbars.nim");
		if (!eqStrings(sortmode_129046, ((NimStringDesc*) &TMP274))) goto LA31;
		nimln(51, "vbars.nim");
		memset((void*)(&LOC33), 0, sizeof(LOC33));
		LOC33.ClPrc = ((TMP293) (HEX3Aanonymous_129189)); LOC33.ClEnv = NIM_NIL;
		sort_129215(values_129040->data, values_129040->Sup.len, LOC33, ((NU8) 1));
	}
	LA31: ;
	nimln(54, "vbars.nim");
	{
		TY129234 LOC38;
		nimln(54, "vbars.nim");
		if (!eqStrings(sortmode_129046, ((NimStringDesc*) &TMP272))) goto LA36;
		nimln(55, "vbars.nim");
		memset((void*)(&LOC38), 0, sizeof(LOC38));
		LOC38.ClPrc = ((TMP294) (HEX3Aanonymous_130689)); LOC38.ClEnv = NIM_NIL;
		sort_129215(values_129040->data, values_129040->Sup.len, LOC38, ((NU8) 1));
	}
	LA36: ;
	{
		NI i_130894;
		NI l_130896;
		nimln(2986, "system.nim");
		i_130894 = 0;
		nimln(2987, "system.nim");
		nimln(2987, "system.nim");
		l_130896 = values_129040->Sup.len;
		{
			nimln(2988, "system.nim");
			while (1) {
				NimStringDesc* LOC42;
				NI i;
				charseq127019* s;
				NF top;
				NF looprange;
				NimStringDesc* last;
				NimStringDesc* LOC55;
				NimStringDesc* LOC56;
				nimln(2988, "system.nim");
				if (!(i_130894 < l_130896)) goto LA41;
				nimln(2989, "system.nim");
				if ((NU)(i_130894) >= (NU)(values_129040->Sup.len)) raiseIndexError();
				LOC42 = 0;
				LOC42 = e_130822.Field0; e_130822.Field0 = copyStringRC1(values_129040->data[i_130894].Field0);
				if (LOC42) nimGCunrefNoCycle(LOC42);
				e_130822.Field1 = values_129040->data[i_130894].Field1;
				nimln(59, "vbars.nim");
				nimln(59, "vbars.nim");
				printf("%s\012", (e_130822.Field0)->data);
				nimln(60, "vbars.nim");
				i = 0;
				nimln(61, "vbars.nim");
				s = (charseq127019*) newSeq((&NTI127019), 0);
				nimln(62, "vbars.nim");
				nimln(63, "vbars.nim");
				{
					nimln(63, "vbars.nim");
					if (!(high_129044 < e_130822.Field1)) goto LA45;
					top = high_129044;
				}
				goto LA43;
				LA45: ;
				{
					top = e_130822.Field1;
				}
				LA43: ;
				nimln(65, "vbars.nim");
				nimln(65, "vbars.nim");
				nimln(65, "vbars.nim");
				nimln(65, "vbars.nim");
				nimln(65, "vbars.nim");
				looprange = ((NF)(((NF)(((NF)(top) - (NF)(low_129042))) / (NF)(((NF)(high_129044) - (NF)(low_129042))))) * (NF)(8.0000000000000000e+01));
				{
					nimln(66, "vbars.nim");
					while (1) {
						nimln(66, "vbars.nim");
						nimln(66, "vbars.nim");
						if (!(i < float64ToInt32(looprange))) goto LA49;
						nimln(67, "vbars.nim");
						s = (charseq127019*) incrSeq(&(s)->Sup, sizeof(NIM_CHAR));
						s->data[s->Sup.len-1] = 61;
						nimln(68, "vbars.nim");
						i = addInt(i, 1);
					} LA49: ;
				}
				nimln(69, "vbars.nim");
				nimln(70, "vbars.nim");
				{
					nimln(70, "vbars.nim");
					if (!(e_130822.Field1 == top)) goto LA52;
					last = copyString(((NimStringDesc*) &TMP295));
				}
				goto LA50;
				LA52: ;
				{
					last = copyString(((NimStringDesc*) &TMP296));
				}
				LA50: ;
				nimln(72, "vbars.nim");
				nimln(72, "vbars.nim");
				nimln(72, "vbars.nim");
				LOC55 = 0;
				LOC55 = nimFloatToStr(low_129042);
				nimln(72, "vbars.nim");
				nimln(72, "vbars.nim");
				nimln(72, "vbars.nim");
				nimln(72, "vbars.nim");
				nimln(72, "vbars.nim");
				LOC56 = 0;
				LOC56 = nimFloatToStr(e_130822.Field1);
				nimln(72, "vbars.nim");
				printf("%s%s%s%s%s%s\012", (LOC55)->data, (((NimStringDesc*) &TMP297))->data, (((NimStringDesc*) (s)))->data, (((NimStringDesc*) &TMP297))->data, (LOC56)->data, (last)->data);
				nimln(2990, "system.nim");
				i_130894 = addInt(i_130894, 1);
				nimln(2991, "system.nim");
				{
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					if (!!((values_129040->Sup.len == l_130896))) goto LA59;
					nimln(2991, "system.nim");
					failedassertimpl_85425(((NimStringDesc*) &TMP298));
				}
				LA59: ;
			} LA41: ;
		}
	}
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, vbarsDatInit)(void) {
static TNimNode* TMP264[2];
static TNimNode TMP129[3];
NTI129013.size = sizeof(datapair129013);
NTI129013.kind = 18;
NTI129013.base = 0;
NTI129013.flags = 2;
TMP264[0] = &TMP129[1];
TMP129[1].kind = 1;
TMP129[1].offset = offsetof(datapair129013, Field0);
TMP129[1].typ = (&NTI149);
TMP129[1].name = "Field0";
TMP264[1] = &TMP129[2];
TMP129[2].kind = 1;
TMP129[2].offset = offsetof(datapair129013, Field1);
TMP129[2].typ = (&NTI128);
TMP129[2].name = "Field1";
TMP129[0].len = 2; TMP129[0].kind = 2; TMP129[0].sons = &TMP264[0];
NTI129013.node = &TMP129[0];
NTI129019.size = sizeof(TY129019*);
NTI129019.kind = 24;
NTI129019.base = (&NTI129013);
NTI129019.flags = 2;
NTI129019.marker = TMP265;
}

